before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: xbpVweAhV7hPb9xzrvRirYNWGVqiLpUlyn1k/JGNA+Jon9ZXdydsm5w2D8dO8MEqiNCuhGkhSq4kal1aTg10BTA6Z1XMQVu5H+hTrfP8uLerm1dq7wGogxYdJ3Dvr88Rl7eLxGhSOENU4lT01ziVsd4Ro2Qbldmrlx0BOji/W3T8RV8iP08PzlsFskN3nRY88Vca73jomtHrokocp5CbUL+5ngK19S3USRvA40/EW3KRx7TQNAKeSGxu4LJBIZOYLsV8IMt5M5HbLGYFcKcnEfcJHPi81c4xiWHwlEYGg2DSOEoIlh9Anm4Ihkj+IYWLXq7OuVBi4QNVWz6Gl4YLlkNhWpHl4C3beQr/AOEhKPHf8exNQO1jM17J45DF3xFFuzvMO70t2rtos3sdNak7hb7pERGiBoj1EFHzAVO6nBzrMu0j7OyHM5LcEWgdsYhzjp5UxchVJ/QTKQ06l6RRXBd+KPscR0zFLNN3iefc/zo9/OLeQWmMxhY2qQjdC6L7jNDV63TGWPKFQV22c9NIpn8Puzrg0ZtxqpE9Dphy43s/X7p184gTUp5Y7Vp7Q8shYUUERTK6KDXAe7cvA6WpDwfdi3c1svuAWWj/pUbHhH+EwueNHhxP6b0enOJCppWIosQQGu4rjB4t944tr6zwbaEazU5NKoJXStWNDs9/I/M= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
